language: rust
cache: cargo
matrix:
  include:
  - env: TARGET=x86_64-unknown-linux-gnu
    os: linux
      apt:
        packages:
            -libusb-dev
install:
- cargo fetch
- rustup target add armv7-unknown-linux-gnueabihf
- rustup component add rustfmt
script:
- cargo build && cargo test && cargo build --target=$TARGET --release
before_deploy:
- tar -cvf target/cp2130-util-$TARGET-$TRAVIS_TAG.tgz -C target/$TARGET/release/ cp2130-util
notifications:
  email:
    on_success: never
    on_failure: never
deploy:
  provider: releases
  api_key:
    secure: Q2lL9ZYBlGUeBHtGg24X7vbm2RXQnPkE12j4dntvYoxb3wUHAUpFtO8bl9opoMCk2cKY+G9cv4hLLmgm6h9jck+2dnqXqeWJuaYVAqMzarwugJyGJ8CmreMV+FHrapVBJ6ZBMX/JEzUBpjUCWPWRcuegh9cOUzNT7DwGh3hTgaBQYYeQNSQZmsgdhhQJoQPRoOHCLzxQ6sPfeQv+LADdTfomNyyXfIzFy2NuB9pwx4YUvXgGmjR23WKfCp+iG3GrmisXUCzfsHLE7iZOg9kHaNyrIQFzZ3UbcmW8zfkkMB0CaeblIRK1HqNKflJHP9+WeRbNbxpqaRj8qnp6lf+xxtFbK5yy744Wpu+beeS1tDNr/IslWkf/yV5lAehN9S6YnrJMwA3mTbJnCqZ3Ffbl62XWksbrdmRZ7n3mcAC27MdvEdScAiCuDtw+P5wdIixawZkKFOvQvJ+Vt1i3TaLyFALqcVumuNWKpLG7jRgXXQyx+uHIbEvch4pF3+z5xqup5oDr5hHew7Jes4dKDPQmxKrUmP1FUUI14oEtYdxR7IijEPwxk0O/5qhY5EBDU7X8yL+MaB6fCx1a6jZ9nYMJvZUV/aAycQPPR0Yv+UhVbhZ2mauhzOf2JNm/Vh5oJXGKS+sZuVZwXYzUVWK0okYJUDwPegDAFo8aIwAP5Gp0OS4=
  file: target/*.tgz
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: ryankurte/rust-driver-cp2130
